# Generated by Django 6.0.3 on 2026-03-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chat_document_chat_flashcard_message_notesummary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(default=list),
        ),
    ]
